sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5npE3wapGmA3d3VTKQ
    access-key-secret: ZqSAMjUyMqme72Do1boK6GPFvUMyjT
    bucket-name: sq-swag
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 12
  wechat:
    appid: wx2782ec23babeedb8
    secret: e639782510daad58fdc0c44cb76a2be3
